/********************************************************************
* src/TreeData/CintDictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/TreeData/CintDictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableCintDictionary();
extern void G__cpp_setup_inheritanceCintDictionary();
extern void G__cpp_setup_typetableCintDictionary();
extern void G__cpp_setup_memvarCintDictionary();
extern void G__cpp_setup_globalCintDictionary();
extern void G__cpp_setup_memfuncCintDictionary();
extern void G__cpp_setup_funcCintDictionary();
extern void G__set_cpp_environmentCintDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "CandidateEvent.h"
#include "CandidateEventPlane.h"
#include "CandidatePair.h"
#include "CandidateTrack.h"
#include "CandidateTrackBTofPidTraits.h"
#include "CandidateTrackEmcPidTraits.h"
#include "CandidateTrackHelix.h"
#include "CandidateTrackMtdPidTraits.h"
#include "PythiaTrack.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CintDictionaryLN_TClass;
extern G__linked_taginfo G__CintDictionaryLN_TBuffer;
extern G__linked_taginfo G__CintDictionaryLN_TMemberInspector;
extern G__linked_taginfo G__CintDictionaryLN_TObject;
extern G__linked_taginfo G__CintDictionaryLN_string;
extern G__linked_taginfo G__CintDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__CintDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CintDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__CintDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CintDictionaryLN_CandidateEvent;
extern G__linked_taginfo G__CintDictionaryLN_CandidateEventPlane;
extern G__linked_taginfo G__CintDictionaryLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__CintDictionaryLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__CintDictionaryLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__CintDictionaryLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__CintDictionaryLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__CintDictionaryLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__CintDictionaryLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__CintDictionaryLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__CintDictionaryLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__CintDictionaryLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__CintDictionaryLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__CintDictionaryLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__CintDictionaryLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__CintDictionaryLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__CintDictionaryLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__CintDictionaryLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__CintDictionaryLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__CintDictionaryLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__CintDictionaryLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__CintDictionaryLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__CintDictionaryLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__CintDictionaryLN_TVector3;
extern G__linked_taginfo G__CintDictionaryLN_TLorentzVector;
extern G__linked_taginfo G__CintDictionaryLN_CandidateTrack;
extern G__linked_taginfo G__CintDictionaryLN_CandidateTrackMtdPidTraits;
extern G__linked_taginfo G__CintDictionaryLN_CandidatePair;
extern G__linked_taginfo G__CintDictionaryLN_CandidateTrackBTofPidTraits;
extern G__linked_taginfo G__CintDictionaryLN_CandidateTrackEmcPidTraits;
extern G__linked_taginfo G__CintDictionaryLN_CandidateTrackHelix;
extern G__linked_taginfo G__CintDictionaryLN_PythiaTrack;

/* STUB derived class for protected member access */
