/********************************************************************
* src/PicoDstClassLibrary/PicoDictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/PicoDstClassLibrary/PicoDictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePicoDictionary();
extern void G__cpp_setup_inheritancePicoDictionary();
extern void G__cpp_setup_typetablePicoDictionary();
extern void G__cpp_setup_memvarPicoDictionary();
extern void G__cpp_setup_globalPicoDictionary();
extern void G__cpp_setup_memfuncPicoDictionary();
extern void G__cpp_setup_funcPicoDictionary();
extern void G__set_cpp_environmentPicoDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "StPicoBTOWHit.h"
#include "StPicoBTofHit.h"
#include "StPicoBTofPidTraits.h"
#include "StPicoEmcPidTraits.h"
#include "StPicoEmcTrigger.h"
#include "StPicoEvent.h"
#include "StPicoMtdHit.h"
#include "StPicoMtdPidTraits.h"
#include "StPicoMtdTrigger.h"
#include "StPicoTrack.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PicoDictionaryLN_TClass;
extern G__linked_taginfo G__PicoDictionaryLN_TBuffer;
extern G__linked_taginfo G__PicoDictionaryLN_TMemberInspector;
extern G__linked_taginfo G__PicoDictionaryLN_TObject;
extern G__linked_taginfo G__PicoDictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__PicoDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PicoDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PicoDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__PicoDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PicoDictionaryLN_StPicoBTOWHit;
extern G__linked_taginfo G__PicoDictionaryLN_StPicoBTofHit;
extern G__linked_taginfo G__PicoDictionaryLN_StThreeVectorlEfloatgR;
extern G__linked_taginfo G__PicoDictionaryLN_StPicoBTofPidTraits;
extern G__linked_taginfo G__PicoDictionaryLN_StPicoEmcPidTraits;
extern G__linked_taginfo G__PicoDictionaryLN_StPicoEmcTrigger;
extern G__linked_taginfo G__PicoDictionaryLN_StPicoEvent;
extern G__linked_taginfo G__PicoDictionaryLN_StPicoMtdHit;
extern G__linked_taginfo G__PicoDictionaryLN_pairlEfloatcOfloatgR;
extern G__linked_taginfo G__PicoDictionaryLN_StPicoMtdPidTraits;
extern G__linked_taginfo G__PicoDictionaryLN_StPicoMtdTrigger;
extern G__linked_taginfo G__PicoDictionaryLN_StPhysicalHelix;
extern G__linked_taginfo G__PicoDictionaryLN_StDcaGeometry;
extern G__linked_taginfo G__PicoDictionaryLN_StPicoTrack;

/* STUB derived class for protected member access */
